export const USER_ACTION_TYPES = {
    LOGGING:'LOGGING',
    LOGIN_START:'LOGIN_START',
    LOGIN_WITH_GOOGLE_START:'LOGIN_WITH_GOOGLE_START',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    CHECK_USER_SESSION:'CHECK_USER_SESSION'
}